### ISSUE TITLE
General Usage

### ISSUE THREAD

**Issue by sakaye** [razorbacks/laravel-shibboleth#8]
Hello,

I am trying to use this for my school's website to access our shibboleth IdP. I had a couple questions. Thanks.

1. Do I need to install shibboleth SP on my local machine in order to connect to our IdP?
2. If #1 is true; is it better to use shibbalike for local development?
3. Where do I place the metadata file in my local file structure?

**Comment by jpuck** [comment]
1. Yes. The server that runs the laravel site needs to have the SP installed and running.
2. Probably. I have the full SP installed on my development machine with a few virtual hosts configured, so that's my personal development workflow. I don't ever use Shibalike, but it seems that's the more popular option for developers.
3. Not sure what you're asking. The metadata file is generated by the SP and can be downloaded by visiting `/Shibboleth.sso/Metadata` in a web browser. This file will need to be submitted to the IdP in order for authentication to work.

For more information about setting up the SP: https://github.com/razorbacks/ubuntu-authentication/blob/master/shibboleth/README.md

**Comment by sakaye** [comment]
Thanks @jpuck for the feedback.
